/* Generated by tools/patcher/make_patch.ps1 after plist.txt is updated.
   Loaded by the Launcher UI as a cross-origin script; keep this ES5. */
window.MIDNIGHT_PATCH_STATUS = {
    latestIndex: 144,
    latestFile: '0144_20261002_hotfix-iteminfo-dungeon-scroll.thor',
    updatedAt: '2026-10-02T07:18:19+07:00'
};
