/* Generated by tools/patcher/make_patch.ps1 after plist.txt is updated.
   Loaded by the Launcher UI as a cross-origin script; keep this ES5. */
window.MIDNIGHT_PATCH_STATUS = {
    latestIndex: 112,
    latestFile: '0112_20260914_costume-baseline-tooltip-loose-fix.thor',
    updatedAt: '2026-09-14T22:54:56+07:00'
};
