/* Generated by tools/patcher/make_patch.ps1 after plist.txt is updated.
   Loaded by the Launcher UI as a cross-origin script; keep this ES5. */
window.MIDNIGHT_PATCH_STATUS = {
    latestIndex: 106,
    latestFile: '0106_20260913_event-moon-items.thor',
    updatedAt: '2026-09-13T00:15:04+07:00'
};
